import { AutoGeneratedNumericKeyEntity } from '../helpers/persistence/base.entity';

export type AuditEntity = AutoGeneratedNumericKeyEntity & {

  date: Date,
  details: string | null,
  entityId: string,
  fromState: string | null,
  toState: string,

}
