export type CreateNonEnumeratedItemResponseDTO = {
  brandCode: string,
  brandName: string,
  card: string | null,
  certVersion: string,
  claimCode: string | null,
  code: string,
  description: string,
  flexHost: string,
  maxQty: number | null,
  nftAddress: string | null,
  nftState: string,
  ownerAddress: string | null,
  platformCode: string,
  recommendedRetailPrice: number | null,
  saleQty: number | null,
  sknappHost: string,
  source: string,
  state: string,
  stockKeepingUnitCode: string,
  stockKeepingUnitName: string,
  stockKeepingUnitRarity: number | null,
  thumbprint: string,
  version: string,
}
